/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PathlessLayoutRouteRouteImport } from './routes/_pathlessLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathlessLayoutSoldIndexRouteImport } from './routes/_pathlessLayout/sold/index'
import { Route as PathlessLayoutEventsIndexRouteImport } from './routes/_pathlessLayout/events/index'
import { Route as PathlessLayoutBlogIndexRouteImport } from './routes/_pathlessLayout/blog/index'
import { Route as PathlessLayoutArtworksIndexRouteImport } from './routes/_pathlessLayout/artworks/index'
import { Route as PathlessLayoutArtistsIndexRouteImport } from './routes/_pathlessLayout/artists/index'
import { Route as PathlessLayoutAboutIndexRouteImport } from './routes/_pathlessLayout/about/index'
import { Route as ApiShopifyGraphqlRouteImport } from './routes/api/shopify/graphql'
import { Route as PathlessLayoutBlogSlugRouteImport } from './routes/_pathlessLayout/blog/$slug'
import { Route as PathlessLayoutLegalSlugIndexRouteImport } from './routes/_pathlessLayout/legal/$slug.index'
import { Route as PathlessLayoutArtworksSlugIndexRouteImport } from './routes/_pathlessLayout/artworks/$slug.index'
import { Route as PathlessLayoutArtistsSlugIndexRouteImport } from './routes/_pathlessLayout/artists/$slug/index'
import { Route as PathlessLayoutEventsFairsSlugIndexRouteImport } from './routes/_pathlessLayout/events/fairs/$slug.index'
import { Route as PathlessLayoutEventsExhibitionsSlugIndexRouteImport } from './routes/_pathlessLayout/events/exhibitions/$slug.index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRouteRoute = PathlessLayoutRouteRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutSoldIndexRoute = PathlessLayoutSoldIndexRouteImport.update({
  id: '/sold/',
  path: '/sold/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutEventsIndexRoute =
  PathlessLayoutEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutBlogIndexRoute = PathlessLayoutBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutArtworksIndexRoute =
  PathlessLayoutArtworksIndexRouteImport.update({
    id: '/artworks/',
    path: '/artworks/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutArtistsIndexRoute =
  PathlessLayoutArtistsIndexRouteImport.update({
    id: '/artists/',
    path: '/artists/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutAboutIndexRoute =
  PathlessLayoutAboutIndexRouteImport.update({
    id: '/about/',
    path: '/about/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const ApiShopifyGraphqlRoute = ApiShopifyGraphqlRouteImport.update({
  id: '/api/shopify/graphql',
  path: '/api/shopify/graphql',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutBlogSlugRoute = PathlessLayoutBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => PathlessLayoutRouteRoute,
} as any)
const PathlessLayoutLegalSlugIndexRoute =
  PathlessLayoutLegalSlugIndexRouteImport.update({
    id: '/legal/$slug/',
    path: '/legal/$slug/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutArtworksSlugIndexRoute =
  PathlessLayoutArtworksSlugIndexRouteImport.update({
    id: '/artworks/$slug/',
    path: '/artworks/$slug/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutArtistsSlugIndexRoute =
  PathlessLayoutArtistsSlugIndexRouteImport.update({
    id: '/artists/$slug/',
    path: '/artists/$slug/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutEventsFairsSlugIndexRoute =
  PathlessLayoutEventsFairsSlugIndexRouteImport.update({
    id: '/events/fairs/$slug/',
    path: '/events/fairs/$slug/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)
const PathlessLayoutEventsExhibitionsSlugIndexRoute =
  PathlessLayoutEventsExhibitionsSlugIndexRouteImport.update({
    id: '/events/exhibitions/$slug/',
    path: '/events/exhibitions/$slug/',
    getParentRoute: () => PathlessLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof PathlessLayoutBlogSlugRoute
  '/api/shopify/graphql': typeof ApiShopifyGraphqlRoute
  '/about/': typeof PathlessLayoutAboutIndexRoute
  '/artists/': typeof PathlessLayoutArtistsIndexRoute
  '/artworks/': typeof PathlessLayoutArtworksIndexRoute
  '/blog/': typeof PathlessLayoutBlogIndexRoute
  '/events/': typeof PathlessLayoutEventsIndexRoute
  '/sold/': typeof PathlessLayoutSoldIndexRoute
  '/artists/$slug/': typeof PathlessLayoutArtistsSlugIndexRoute
  '/artworks/$slug/': typeof PathlessLayoutArtworksSlugIndexRoute
  '/legal/$slug/': typeof PathlessLayoutLegalSlugIndexRoute
  '/events/exhibitions/$slug/': typeof PathlessLayoutEventsExhibitionsSlugIndexRoute
  '/events/fairs/$slug/': typeof PathlessLayoutEventsFairsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof PathlessLayoutBlogSlugRoute
  '/api/shopify/graphql': typeof ApiShopifyGraphqlRoute
  '/about': typeof PathlessLayoutAboutIndexRoute
  '/artists': typeof PathlessLayoutArtistsIndexRoute
  '/artworks': typeof PathlessLayoutArtworksIndexRoute
  '/blog': typeof PathlessLayoutBlogIndexRoute
  '/events': typeof PathlessLayoutEventsIndexRoute
  '/sold': typeof PathlessLayoutSoldIndexRoute
  '/artists/$slug': typeof PathlessLayoutArtistsSlugIndexRoute
  '/artworks/$slug': typeof PathlessLayoutArtworksSlugIndexRoute
  '/legal/$slug': typeof PathlessLayoutLegalSlugIndexRoute
  '/events/exhibitions/$slug': typeof PathlessLayoutEventsExhibitionsSlugIndexRoute
  '/events/fairs/$slug': typeof PathlessLayoutEventsFairsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_pathlessLayout/blog/$slug': typeof PathlessLayoutBlogSlugRoute
  '/api/shopify/graphql': typeof ApiShopifyGraphqlRoute
  '/_pathlessLayout/about/': typeof PathlessLayoutAboutIndexRoute
  '/_pathlessLayout/artists/': typeof PathlessLayoutArtistsIndexRoute
  '/_pathlessLayout/artworks/': typeof PathlessLayoutArtworksIndexRoute
  '/_pathlessLayout/blog/': typeof PathlessLayoutBlogIndexRoute
  '/_pathlessLayout/events/': typeof PathlessLayoutEventsIndexRoute
  '/_pathlessLayout/sold/': typeof PathlessLayoutSoldIndexRoute
  '/_pathlessLayout/artists/$slug/': typeof PathlessLayoutArtistsSlugIndexRoute
  '/_pathlessLayout/artworks/$slug/': typeof PathlessLayoutArtworksSlugIndexRoute
  '/_pathlessLayout/legal/$slug/': typeof PathlessLayoutLegalSlugIndexRoute
  '/_pathlessLayout/events/exhibitions/$slug/': typeof PathlessLayoutEventsExhibitionsSlugIndexRoute
  '/_pathlessLayout/events/fairs/$slug/': typeof PathlessLayoutEventsFairsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/api/shopify/graphql'
    | '/about/'
    | '/artists/'
    | '/artworks/'
    | '/blog/'
    | '/events/'
    | '/sold/'
    | '/artists/$slug/'
    | '/artworks/$slug/'
    | '/legal/$slug/'
    | '/events/exhibitions/$slug/'
    | '/events/fairs/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/api/shopify/graphql'
    | '/about'
    | '/artists'
    | '/artworks'
    | '/blog'
    | '/events'
    | '/sold'
    | '/artists/$slug'
    | '/artworks/$slug'
    | '/legal/$slug'
    | '/events/exhibitions/$slug'
    | '/events/fairs/$slug'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/sitemap.xml'
    | '/_pathlessLayout/blog/$slug'
    | '/api/shopify/graphql'
    | '/_pathlessLayout/about/'
    | '/_pathlessLayout/artists/'
    | '/_pathlessLayout/artworks/'
    | '/_pathlessLayout/blog/'
    | '/_pathlessLayout/events/'
    | '/_pathlessLayout/sold/'
    | '/_pathlessLayout/artists/$slug/'
    | '/_pathlessLayout/artworks/$slug/'
    | '/_pathlessLayout/legal/$slug/'
    | '/_pathlessLayout/events/exhibitions/$slug/'
    | '/_pathlessLayout/events/fairs/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRouteRoute: typeof PathlessLayoutRouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiShopifyGraphqlRoute: typeof ApiShopifyGraphqlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/sold/': {
      id: '/_pathlessLayout/sold/'
      path: '/sold'
      fullPath: '/sold/'
      preLoaderRoute: typeof PathlessLayoutSoldIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/events/': {
      id: '/_pathlessLayout/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof PathlessLayoutEventsIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/blog/': {
      id: '/_pathlessLayout/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PathlessLayoutBlogIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/artworks/': {
      id: '/_pathlessLayout/artworks/'
      path: '/artworks'
      fullPath: '/artworks/'
      preLoaderRoute: typeof PathlessLayoutArtworksIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/artists/': {
      id: '/_pathlessLayout/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof PathlessLayoutArtistsIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/about/': {
      id: '/_pathlessLayout/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof PathlessLayoutAboutIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/api/shopify/graphql': {
      id: '/api/shopify/graphql'
      path: '/api/shopify/graphql'
      fullPath: '/api/shopify/graphql'
      preLoaderRoute: typeof ApiShopifyGraphqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/blog/$slug': {
      id: '/_pathlessLayout/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PathlessLayoutBlogSlugRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/legal/$slug/': {
      id: '/_pathlessLayout/legal/$slug/'
      path: '/legal/$slug'
      fullPath: '/legal/$slug/'
      preLoaderRoute: typeof PathlessLayoutLegalSlugIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/artworks/$slug/': {
      id: '/_pathlessLayout/artworks/$slug/'
      path: '/artworks/$slug'
      fullPath: '/artworks/$slug/'
      preLoaderRoute: typeof PathlessLayoutArtworksSlugIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/artists/$slug/': {
      id: '/_pathlessLayout/artists/$slug/'
      path: '/artists/$slug'
      fullPath: '/artists/$slug/'
      preLoaderRoute: typeof PathlessLayoutArtistsSlugIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/events/fairs/$slug/': {
      id: '/_pathlessLayout/events/fairs/$slug/'
      path: '/events/fairs/$slug'
      fullPath: '/events/fairs/$slug/'
      preLoaderRoute: typeof PathlessLayoutEventsFairsSlugIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
    '/_pathlessLayout/events/exhibitions/$slug/': {
      id: '/_pathlessLayout/events/exhibitions/$slug/'
      path: '/events/exhibitions/$slug'
      fullPath: '/events/exhibitions/$slug/'
      preLoaderRoute: typeof PathlessLayoutEventsExhibitionsSlugIndexRouteImport
      parentRoute: typeof PathlessLayoutRouteRoute
    }
  }
}

interface PathlessLayoutRouteRouteChildren {
  PathlessLayoutBlogSlugRoute: typeof PathlessLayoutBlogSlugRoute
  PathlessLayoutAboutIndexRoute: typeof PathlessLayoutAboutIndexRoute
  PathlessLayoutArtistsIndexRoute: typeof PathlessLayoutArtistsIndexRoute
  PathlessLayoutArtworksIndexRoute: typeof PathlessLayoutArtworksIndexRoute
  PathlessLayoutBlogIndexRoute: typeof PathlessLayoutBlogIndexRoute
  PathlessLayoutEventsIndexRoute: typeof PathlessLayoutEventsIndexRoute
  PathlessLayoutSoldIndexRoute: typeof PathlessLayoutSoldIndexRoute
  PathlessLayoutArtistsSlugIndexRoute: typeof PathlessLayoutArtistsSlugIndexRoute
  PathlessLayoutArtworksSlugIndexRoute: typeof PathlessLayoutArtworksSlugIndexRoute
  PathlessLayoutLegalSlugIndexRoute: typeof PathlessLayoutLegalSlugIndexRoute
  PathlessLayoutEventsExhibitionsSlugIndexRoute: typeof PathlessLayoutEventsExhibitionsSlugIndexRoute
  PathlessLayoutEventsFairsSlugIndexRoute: typeof PathlessLayoutEventsFairsSlugIndexRoute
}

const PathlessLayoutRouteRouteChildren: PathlessLayoutRouteRouteChildren = {
  PathlessLayoutBlogSlugRoute: PathlessLayoutBlogSlugRoute,
  PathlessLayoutAboutIndexRoute: PathlessLayoutAboutIndexRoute,
  PathlessLayoutArtistsIndexRoute: PathlessLayoutArtistsIndexRoute,
  PathlessLayoutArtworksIndexRoute: PathlessLayoutArtworksIndexRoute,
  PathlessLayoutBlogIndexRoute: PathlessLayoutBlogIndexRoute,
  PathlessLayoutEventsIndexRoute: PathlessLayoutEventsIndexRoute,
  PathlessLayoutSoldIndexRoute: PathlessLayoutSoldIndexRoute,
  PathlessLayoutArtistsSlugIndexRoute: PathlessLayoutArtistsSlugIndexRoute,
  PathlessLayoutArtworksSlugIndexRoute: PathlessLayoutArtworksSlugIndexRoute,
  PathlessLayoutLegalSlugIndexRoute: PathlessLayoutLegalSlugIndexRoute,
  PathlessLayoutEventsExhibitionsSlugIndexRoute:
    PathlessLayoutEventsExhibitionsSlugIndexRoute,
  PathlessLayoutEventsFairsSlugIndexRoute:
    PathlessLayoutEventsFairsSlugIndexRoute,
}

const PathlessLayoutRouteRouteWithChildren =
  PathlessLayoutRouteRoute._addFileChildren(PathlessLayoutRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRouteRoute: PathlessLayoutRouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiShopifyGraphqlRoute: ApiShopifyGraphqlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
